# Generated by Django 3.2 on 2022-07-31 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст заявителя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('is_approved', models.BooleanField(blank=True, null=True, verbose_name='одобрено')),
            ],
            options={
                'verbose_name': 'Заявка на получение прав арендодателя',
                'verbose_name_plural': 'Заявки на получение прав арендодателя',
            },
        ),
    ]
