# Generated by Django 3.2 on 2022-07-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_claim_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='text',
            field=models.TextField(blank=True, verbose_name='текст заявителя'),
        ),
    ]
